### ISSUE TITLE
Extend dataset method to incorporate MixedModels datasets

### ISSUE THREAD

**Issue by dmbates** [JuliaMixedModels/EmbraceUncertainty#32]
I propose that we have all the datasets that we use available through the `EmbraceUncertainty.dataset` generic and remove the `data` directory.

For the purposes of the book `dataset(:foo)` will mean `EmbraceUncertainty.dataset(:foo)`.

Those datasets that are available through `MixedModels.dataset` will be grandfathered into EmbraceUncertainty.dataset by checking the names against the result of `MixedModels.datasets()`.

Data tables from the English Lexicon Project are available in the `arrow` directory of https://github.com/dmbates/EnglishLexicon.jl

The datasets used in the longitudinal data chapter are available in the osf.io repository https://osf.io/sr46c/.

For the time being I think I will just customize the dataset retrieval for each name just so we can get it working.  Later we can decide if there should be a unified storage and retrieval protocol.

**Comment by palday** [comment]
I like this idea
