### ISSUE TITLE
Shall we bump the jupyter kernel spec to julia-1.10?

### ISSUE THREAD

**Issue by dmbates** [JuliaMixedModels/EmbraceUncertainty#38]
Now that the release version of Julia is 1.10.0 I don't have a julia-1.9 IJulia kernel accessible through juliaup without adding it explicitly.  @palday Would it be okay to bump the `jupyter` setting in the files in this repository to `julia-1.10`?

**Comment by kliegl** [comment]
Me, too.Sent from my iPadOn 27. Dec 2023, at 17:49, Phillip Alday ***@***.***> wrote:﻿
I'm fine with that.

**Comment by dmbates** [comment]
Looks like this won't work out right now.  It looks as if there are more consistency checks in 1.10 that cause some `AlgebraOfGraphics` code to throw errors  https://github.com/MakieOrg/AlgebraOfGraphics.jl/issues/472  I'll follow that issue to see if it gets resolved - otherwise we may need to rewrite many of those plots using AlgebraOfGraphics as direct calls to Makie functions.

**Comment by dmbates** [comment]
@palday has a PR on the Dictionaries.jl repository to resolve https://githiub.com/MakieOrg/AlgebraOfGraphics#472.  We will need to wait until this issue is resolved before switching to julia-1.10

**Comment by dmbates** [comment]
Closed via #43
