### ISSUE TITLE
Take advantage of recent changes in MixedModels.jl

### ISSUE THREAD

**Issue by dmbates** [JuliaMixedModels/EmbraceUncertainty#39]
Currently we assign `Grouping()` contrasts to any grouping factors.  In the past it was necessary to do this to avoid unnecessarily creating large, dense contrasts matrices when grouping factors had many levels.

After https://github.com/JuliaStats/MixedModels.jl/commit/9ee4a0a9f371eddf9aa68118d96c8a006f4a4d58 we no longer need to so (thanks to @palday).

Shall we remove the explicit assignments of `Grouping()` contrasts?  This will allow us to avoid creating a `contrasts` Dict until late in the second chapter when we apply a +/- 1 encoding to a binary experimental factor.

Also, the `show_progress` named argument to `parametricbootstrap` has been deprecated in favor of `progress`.  It makes sense now to assign
```julia
const progress = false
```
and add a named argument `progress` to calls to `fit` and `parametricbootstrap`.

I will create a PR for these changes if there is no objection.

**Comment by palday** [comment]
Onboard with all of this

**Comment by kliegl** [comment]
Fine with me

**Comment by dmbates** [comment]
Closed via #45
