### ISSUE TITLE
Symbols not being rendered correctly

### ISSUE THREAD

**Issue by ajinkya-k** [JuliaMixedModels/EmbraceUncertainty#58]
Some of the symbols in the code blocks are not being rendered correctly on my browser (Safari on macOS 14.4.1). One example is shown in the screenshot below from [Appendix C2.2](https://embraceuncertaintybook.com/aGHQ.html#encapsulating-the-model-in-a-struct). This issue does not seem to occur consistently. Some of the unicode characters (in fact the same character as in the code chunk displayed) does render correctly in other places on the same page. This issue also happens on Chrome for macOS. 

<img width="765" alt="image" src="https://github.com/JuliaMixedModels/EmbraceUncertainty/assets/5984449/294f8555-5f19-48fb-a83f-c2beebd056f2">

**Comment by dmbates** [comment]
I'm not sure what is behind this problem.  We are seeing it even more in development versions that use https://github.com/PumasAI/QuartoNotebookRender.jl as the evaluation engine for Quarto documents with Julia code blocks.  It may be worthwhile testing if the JuliaMono font, https://github.com/cormullion/juliamono/ helps.  It provides more Unicode glyphs but, as you note, the same character is rendered properly in other places.

**Comment by palday** [comment]
@ajinkya-k I have done some minor software updates and republished the website. On my end, things are looking better -- can you check whether that holds for you?

**Comment by ajinkya-k** [comment]
@palday Thanks! That particular one did get resolved! There is still one and the same section (see image below). Just out of curiosity: what changes did you make? Also, I wonder if this rendering issue is because a pre-release version of quarto is being used?
<img width="774" alt="image" src="https://github.com/JuliaMixedModels/EmbraceUncertainty/assets/5984449/0ff98304-92b6-4aa6-a6be-4051e0b55d01">

**Comment by palday** [comment]
I updated to the absolute latest quarto pre-release and QuartoNotebookRunner.jl releases.

**Comment by palday** [comment]
Hmmm, still seeing some unknown characters in the model output for https://embraceuncertaintybook.com/intro.html#sec-dyestuff2lmm

**Comment by ajinkya-k** [comment]
This behavior also happens when I render them on my local repo, including the exact same places in the text where these characters appear

**Comment by palday** [comment]
It looks like there is a fix coming upstream: https://github.com/quarto-dev/quarto-cli/pull/9740

**Comment by ajinkya-k** [comment]
Has this change been incorporated yet? I installed `quarto 1.5.45` and I still get character rending issues.

**Comment by dmbates** [comment]
Quarto 1.5.45 should have installed version 0.11.1 of the QuartoNotebookRunner package. with commit hash 0rtVI
```
% ls -la ~/.julia/packages/QuartoNotebookRunner 
total 0
drwxr-xr-x    4 dmbates  staff    128 Jun 16 09:31 .
drwxr-xr-x  437 dmbates  staff  13984 Jun  6 09:14 ..
drwxr-xr-x   12 dmbates  staff    384 Jun 16 09:31 0rtVI
drwxr-xr-x   12 dmbates  staff    384 May 29 17:13 kZlRN
```

You may need to reevaluate the code blocks to ensure that the latest version is used.  In the EmbraceUncertainty directory run

```
rm -r docs/ _freeze/ .quarto/
quarto render
```

For me that produces a document without any gliches in the output blocks.

**Comment by ajinkya-k** [comment]
This worked! I had run `quarto render` again after updating but I had not cleared the existing html files, so it was using cached versions.

**Comment by ajinkya-k** [comment]
Looks like the symbols are rendering correctly on the website. Closing the issue.
