### ISSUE TITLE
Create a tagpad generic and methods?

### ISSUE THREAD

**Issue by dmbates** [JuliaMixedModels/EmbraceUncertainty#63]
I think that we should create a function `tagpad` (I'm open to suggestions of another, better name) for the operation of taking subject numbers like `1, 2, ..., 312` and converting them to `"S001", "S002", ..., "S312"`.  It's a one-liner but if we create a generic and methods for it we can enhance it to optionally convert the result to a `PooledArray`  to save space.  When it is written to Arrow and read back in to Julia it can be even more compact because of the way Arrow stores character vectors.  Also, using `Base.Fix2` we can create a functor version like `tagpad("S")` which can be used in a transform or select call as
```
:subj => tagpad("S") => :subj
```

I would propose adding such methods to `EmbraceUncertainty.jl`.  Any objections or better name choices? @kliegl @palday

**Comment by kliegl** [comment]
Makes sense and is fine with me.

**Comment by palday** [comment]
Name is fine, key thing is good docstrings. 😄
